s='HappyEveryday'
#大小写转化，lower(),upper(),函数
a=s.lower()
print(s)
print(a)
print(s.lower())
print(s.upper())
#字符串的分割,split(x)函数，x表示分割位置的字符
a=s.split('y')
print(a)
print(a[0],a[1],a[2],a[3])
#查询字符串中某个字符出现的次数count()函数
print(s.count('p'))
#查询字符串中某个子串第一次出现的位置find()函数
print(s.find('a'))
#endwith(x),startwith(x)查询字符串是否以x开头，结尾
print(s.startswith('ha'))
print(s.endswith('day'))